### ISSUE TITLE
[Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by stnfc** [nfcpy/nfcpy#101]
Hello,
Sorry for creating this issue. 
It seems I have a common python error, but I haven't been able to find a solution.

I'm starting trying to use nfcpy and when I execute python-m nfc, I have the following error:
$ python -m nfc
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\nfc\__init__.py", line 22, in <module>
    from . import clf                                                  # noqa: F401
  File "C:\Python27\lib\site-packages\nfc\clf\__init__.py", line 25, in <module>
    from . import device
  File "C:\Python27\lib\site-packages\nfc\clf\device.py", line 32, in <module>
    from . import transport
  File "C:\Python27\lib\site-packages\nfc\clf\transport.py", line 31, in <module>
    import usb1 as libusb
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "C:\Python27\lib\site-packages\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "C:\Python27\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

I tried with 2 different python 2.7 installer version:
-> Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [**MSC v.1500 64 bit (AMD64)**] on win32
-> Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [**MSC v.1500 32 bit (Intel)**] on win32

Any help would be very appreciated !

thanks in advance.

**Comment by ghxbob** [comment]
Do you not use windows 7 32bit OS?

**Comment by stnfc** [comment]
Many thanks for your answer.
I have a 64-bit Windows version (info from Control panel / System / System type).

**Comment by nehpetsde** [comment]
Have you installed libusb as desribed in [installation](http://nfcpy.readthedocs.io/en/latest/topics/get-started.html#installation)? Especially copied 32-bit and 64-bit DLLs correctly?

> The libusb library for Windows can be downloaded from libusb (Downloads -> Latest Windows Binaries) as a 7z archive. Just unpack and copy MS32\dll\libusb-1.0.dll to C:\Windows\System32 and MS64\dll\libusb-1.0.dll to the C:\Windows\SysWOW64 directory.

**Comment by stnfc** [comment]
I doubled check.
The latest binaries are libusb-1.0.21
In both Windows/system32 and Windows/SysWOW64 I have now libusb-1.0.dll, together with libusb0.dll I had before.

**Comment by stnfc** [comment]
some details to be sure we are weel aligned on libusb-1.0.dll:
in C:\Windows\System32 : version 1.0.21.11156, 95KB, modified in 09-Jan 17
in C:\Windows\SysWOW64 : version 1.0.21.11156, 113KB, modified in 09-Jan 17
I you want me to check something else, do not hesitate.

**Comment by ghxbob** [comment]
I met similar problem, and i turn to win 7 32bit(spent half day to move everything...)

**Comment by stnfc** [comment]
Thank you for the information. I cannot change my windows version.

**Comment by henrycjc** [comment]
Also experiencing this - were you able to find a fix @stnfc?

Windows 10 (Version 1709) x64
Nfcpy 0.13.4
libusb 1.0.22

**Comment by stnfc** [comment]
@henrycjc 
unfortunatly not. It seems that nfcpy only support 32bits version ?

**Comment by stnfc** [comment]
@henrycjc 
I have got a feedback in stackoverflow.
Seems that we have to copy to C:\Windows\SysWOW64 directory MS32\dll\libusb-1.0.dll and not MS64\dll\libusb-1.0.dll as explained in the tutorial.
The issue is now solved on my side.

**Comment by anilulak** [comment]
@stnfc 
Hi. I have the same issue I tried a lot of things. But the thing that I cant understand, should we copy only "libusb-1.0.dll" or the whole directory "MS32\dll\libusb-1.0.dll" ? I have exactly the same error outpu with you.

**Comment by nehpetsde** [comment]
I can not say for sure that the instructions work on more or less recent Windows 10, it's been a while ago that I tested. Hopefully in two weeks I will have a W10 machine for testing.

**Comment by henrycjc** [comment]
I will make a PR with updated docs

**Comment by nehpetsde** [comment]
Many thanks for the PR. Does that also mean it is actually working on Windows 10?

**Comment by henrycjc** [comment]
@nehpetsde Yes, tested and working on Windows 10 (1709).

**Comment by nehpetsde** [comment]
@henrycjc I double the Thanks, it really saves me a lot.

**Comment by ascerx** [comment]
yes as @stnfc said.. its sysWow64 file into system32 folder ..spent 1 hour on this.. thanks guys for your comments
