### ISSUE TITLE
why sdd_res[0] must be 08h in listen_tta() of RC-S380?

### ISSUE THREAD

**Issue by ghxbob** [nfcpy/nfcpy#103]
Hi,

Anyone know why sdd_res[0] must be 08h in listen_tta() of RC-S380? hardware limitation?
   if target.sdd_res[0] != 0x08:
            raise ValueError("sdd_res[0] must be 08h")

**Comment by ghxbob** [comment]
According to ISO 14443-3, SDD_RES[0] is the first byte of UID, UID start with 08 means, uid1 to uid3 is a random number which is dynamically generated.

Does that to say, hardware S380 only support random UID?

**Comment by nehpetsde** [comment]
Yes, this is a hardware limitation that is common to PN53x and RC-S380.

**Comment by ghxbob** [comment]
thanks
