### ISSUE TITLE
Add example scripts to package

### ISSUE THREAD

**Issue by escodebar** [nfcpy/nfcpy#108]
The sample scripts are really useful.

They could be added to `setup.py` to make them runnable from the command line: http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#command-line-scripts

**Comment by nehpetsde** [comment]
Thank you for the suggestion. This would make them part of the install package and impose additional dependencies. It's better to make them separate projects.

**Comment by escodebar** [comment]
I suggest a package with the name `nfcpy.tools`.
