### ISSUE TITLE
nfcpy opens Nfc-Reader only once, than [Errno 19] No such Device

### ISSUE THREAD

**Issue by gerolon** [nfcpy/nfcpy#115]
Hello,
i use nfcpy on Windows to communicate with  my USB-nfc-device "SCL3711". The installation from nfcpy and the usb-drivers and libs seems do be sucessfully done.

My problem is now that i only can connect the target onetime:

clf=nfc.ContactlessFrontend('usb')

works!

but if i close with:
clf.close()

it seems to doesnt work.

The next time i try again i get the following error-msg:

File "C:\SVN\NFCpython\trunk\env\lib\site-packages\nfc\clf\__init__.py", line 75, in __init__
    raise IOError(errno.ENODEV, os.strerror(errno.ENODEV))
IOError: [Errno 19] No such device

Same problem is, when i start the nfc-verification two-times:
![cmd](https://user-images.githubusercontent.com/39952453/40973987-73e877d6-68c6-11e8-913e-32a86288645e.png)

At the second try the access is denied. 

When i remove the usb-nfc-reader and plug in again. it works again one time!

Is this a USBdriver Problem?

**Comment by nehpetsde** [comment]
Plesse run 'python -m nfc -vvv' and post the output of the failing attempt.

**Comment by gerolon** [comment]
Hi Stephen,
thank you for answering so quickly.

I run your command twice. The second time fails again. Here are the los from both:

(env) C:\SVN\NFCpython\trunk>python -m nfc -vvv
This is the 0.13.5 version of nfcpy run in Python 2.7.15
on Windows-7-6.1.7601-SP1
I'm now searching your system for contactless devices
DEBUG:nfc.clf.transport:using libusb-1.0.22
DEBUG:nfc.clf.transport:path matches '^(usb|)$'
INFO:nfc.clf:searching for reader on path usb:001:004
DEBUG:nfc.clf.transport:using libusb-1.0.22
DEBUG:nfc.clf.transport:path matches '^usb(:[0-9]{1,3})(:[0-9]{1,3})?$'
DEBUG:nfc.clf.device:loading pn533 driver for usb:04e6:5591
Level 9:nfc.clf.transport:>>> 0000ff00ff00
Level 9:nfc.clf.pn533:Diagnose 00000102030405060708090a0b0c0d0e0f101112131415
718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d
f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465
768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d
f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5
7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdd
fe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff000102030405
000s
Level 9:nfc.clf.transport:>>> 0000ffffff0109f6d40000000102030405060708090a0b0
0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333
363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5
5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838
868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaaba
aeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d
d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbf
feff0001020304059d00
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ffffff0109f6d50100000102030405060708090a0b0
0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333
363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5
5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838
868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaaba
aeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d
d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbf
feff0001020304059b00
Level 9:nfc.clf.pn533:GetFirmwareVersion  0.100s
Level 9:nfc.clf.transport:>>> 0000ff02fed4022a00
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff06fad50333020707e500
DEBUG:nfc.clf.pn533:chipset is a PN533v2.7
Level 9:nfc.clf.pn533:RFConfiguration 0102 0.100s
Level 9:nfc.clf.transport:>>> 0000ff04fcd4320102f700
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
Level 9:nfc.clf.pn533:RFConfiguration 02000b0a 0.100s
Level 9:nfc.clf.transport:>>> 0000ff06fad43202000b0ae300
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
Level 9:nfc.clf.pn533:RFConfiguration 0400 0.100s
Level 9:nfc.clf.transport:>>> 0000ff04fcd4320400f600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
Level 9:nfc.clf.pn533:RFConfiguration 05010001 0.100s
Level 9:nfc.clf.transport:>>> 0000ff06fad43205010001f300
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
Level 9:nfc.clf.pn533:SetParameters 00 0.100s
Level 9:nfc.clf.transport:>>> 0000ff03fdd412001a00
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed5131800
Level 9:nfc.clf.pn533:ReadRegister a000 0.250s
Level 9:nfc.clf.transport:>>> 0000ff04fcd406a0008600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff04fcd50700012300
Level 9:nfc.clf.pn533:ReadRegister a000a001a002a003a004a005a006a007a008a009a0
00ba00ca00da00ea00fa010a011a012a013a014a015a016a017a018a019a01aa01ba01ca01da0
01fa020a021a022a023a024a025a026a027a028a029a02aa02ba02ca02da02ea02fa030a031a0
033a034a035a036a037a038a039a03aa03ba03ca03da03ea03f 0.250s
Level 9:nfc.clf.transport:>>> 0000ff827ed406a000a001a002a003a004a005a006a007a
a009a00aa00ba00ca00da00ea00fa010a011a012a013a014a015a016a017a018a019a01aa01ba
a01da01ea01fa020a021a022a023a024a025a026a027a028a029a02aa02ba02ca02da02ea02fa
a031a032a033a034a035a036a037a038a039a03aa03ba03ca03da03ea03f4600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff43bdd50700011f5af43f114d85616f2662876aff3
1d85616fff108585158a850ab28504da02321201000200000008e604915507020102000109022
010100803209041500
Level 9:nfc.clf.pn533:ReadRegister a040a041a042a043a044a045a046a047a048a049a0
04ba04ca04da04ea04fa050a051a052a053a054a055a056a057a058a059a05aa05ba05ca05da0
05fa060a061a062a063a064a065a066a067a068a069a06aa06ba06ca06da06ea06fa070a071a0
073a074a075a076a077a078a079a07aa07ba07ca07da07ea07f 0.250s
Level 9:nfc.clf.transport:>>> 0000ff827ed406a040a041a042a043a044a045a046a047a
a049a04aa04ba04ca04da04ea04fa050a051a052a053a054a055a056a057a058a059a05aa05ba
a05da05ea05fa060a061a062a063a064a065a066a067a068a069a06aa06ba06ca06da06ea06fa
a071a072a073a074a075a076a077a078a079a07aa07ba07ca07da07ea07f4600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff43bdd50700000002ffffff0007050402400004070
02400004031e1e03530043004c0033003700310031002d004e004600430026005200570004141
530043004d00200400
Level 9:nfc.clf.pn533:ReadRegister a080a081a082a083a084a085a086a087a088a089a0
08ba08ca08da08ea08fa090a091a092a093a094a095a096a097a098a099a09aa09ba09ca09da0
09fa0a0a0a1a0a2a0a3a0a4a0a5a0a6a0a7a0a8a0a9a0aaa0aba0aca0ada0aea0afa0b0a0b1a0
0b3a0b4a0b5a0b6a0b7a0b8a0b9a0baa0bba0bca0bda0bea0bf 0.250s
Level 9:nfc.clf.transport:>>> 0000ff827ed406a080a081a082a083a084a085a086a087a
a089a08aa08ba08ca08da08ea08fa090a091a092a093a094a095a096a097a098a099a09aa09ba
a09da09ea09fa0a0a0a1a0a2a0a3a0a4a0a5a0a6a0a7a0a8a0a9a0aaa0aba0aca0ada0aea0afa
a0b1a0b2a0b3a0b4a0b5a0b6a0b7a0b8a0b9a0baa0bba0bca0bda0bea0bf4600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff43bdd50700004d006900630072006f00050404030
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff3c00
Level 9:nfc.clf.pn533:ReadRegister a0c0a0c1a0c2a0c3a0c4a0c5a0c6a0c7a0c8a0c9a0
0cba0cca0cda0cea0cfa0d0a0d1a0d2a0d3a0d4a0d5a0d6a0d7a0d8a0d9a0daa0dba0dca0dda0
0dfa0e0a0e1a0e2a0e3a0e4a0e5a0e6a0e7a0e8a0e9a0eaa0eba0eca0eda0eea0efa0f0a0f1a0
0f3a0f4a0f5a0f6a0f7a0f8a0f9a0faa0fba0fca0fda0fea0ff 0.250s
Level 9:nfc.clf.transport:>>> 0000ff827ed406a0c0a0c1a0c2a0c3a0c4a0c5a0c6a0c7a
a0c9a0caa0cba0cca0cda0cea0cfa0d0a0d1a0d2a0d3a0d4a0d5a0d6a0d7a0d8a0d9a0daa0dba
a0dda0dea0dfa0e0a0e1a0e2a0e3a0e4a0e5a0e6a0e7a0e8a0e9a0eaa0eba0eca0eda0eea0efa
a0f1a0f2a0f3a0f4a0f5a0f6a0f7a0f8a0f9a0faa0fba0fca0fda0fea0ff4600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff43bdd50700fffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa00032313132313
39453030333632db00
DEBUG:nfc.clf.pn533:EEPROM   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
DEBUG:nfc.clf.pn533:0xA000: 01 1F 5A F4 3F 11 4D 85 61 6F 26 62 87 6A FF 3F
DEBUG:nfc.clf.pn533:0xA010: 10 1D 85 61 6F FF 10 85 85 15 8A 85 0A B2 85 04
DEBUG:nfc.clf.pn533:0xA020: DA 02 32 12 01 00 02 00 00 00 08 E6 04 91 55 07
DEBUG:nfc.clf.pn533:0xA030: 02 01 02 00 01 09 02 20 00 01 01 00 80 32 09 04
DEBUG:nfc.clf.pn533:0xA040: 00 00 02 FF FF FF 00 07 05 04 02 40 00 04 07 05
DEBUG:nfc.clf.pn533:0xA050: 84 02 40 00 04 03 1E 1E 03 53 00 43 00 4C 00 33
DEBUG:nfc.clf.pn533:0xA060: 00 37 00 31 00 31 00 2D 00 4E 00 46 00 43 00 26
DEBUG:nfc.clf.pn533:0xA070: 00 52 00 57 00 04 14 14 03 53 00 43 00 4D 00 20
DEBUG:nfc.clf.pn533:0xA080: 00 4D 00 69 00 63 00 72 00 6F 00 05 04 04 03 09
DEBUG:nfc.clf.pn533:0xA090: 04 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0A0: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0B0: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0C0: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0D0: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0E0: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
DEBUG:nfc.clf.pn533:0xA0F0: A0 00 32 31 31 32 31 36 33 39 45 30 30 33 36 32
DEBUG:nfc.clf.pn533:write analog settings for Type A 106 kbps
Level 9:nfc.clf.pn533:RFConfiguration 0a5af43f114d85616f266287 0.100s
Level 9:nfc.clf.transport:>>> 0000ff0ef2d4320a5af43f114d85616f266287a100
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
DEBUG:nfc.clf.pn533:write analog settings for Type F 212/424 kbps
Level 9:nfc.clf.pn533:RFConfiguration 0b6aff3f104185616f 0.100s
Level 9:nfc.clf.transport:>>> 0000ff0bf5d4320b6aff3f104185616fa100
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
DEBUG:nfc.clf.pn533:write analog settings for Type B 106 kbps
Level 9:nfc.clf.pn533:RFConfiguration 0cff0485 0.100s
Level 9:nfc.clf.transport:>>> 0000ff06fad4320cff04856600
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
DEBUG:nfc.clf.pn533:write analog settings for 14443-4 212/424/848 kbps
Level 9:nfc.clf.pn533:RFConfiguration 0d85158a850ab28504da 0.100s
Level 9:nfc.clf.transport:>>> 0000ff0cf4d4320d85158a850ab28504da2500
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
INFO:nfc.clf:using SCM Micro SCL3711-NFC&RW PN533v2.7 at usb:001:004
** found SCM Micro SCL3711-NFC&RW PN533v2.7 at usb:001:004
Level 9:nfc.clf.pn533:RFConfiguration 0102 0.100s
Level 9:nfc.clf.transport:>>> 0000ff04fcd4320102f700
Level 9:nfc.clf.transport:<<< 0000ff00ff00
Level 9:nfc.clf.transport:<<< 0000ff02fed533f800
I'm not trying serial devices because you haven't told me
-- add the option '--search-tty' to have me looking
-- but beware that this may break other serial devs

(env) C:\SVN\NFCpython\trunk>python -m nfc -vvv
This is the 0.13.5 version of nfcpy run in Python 2.7.15
on Windows-7-6.1.7601-SP1
I'm now searching your system for contactless devices
DEBUG:nfc.clf.transport:using libusb-1.0.22
DEBUG:nfc.clf.transport:path matches '^(usb|)$'
INFO:nfc.clf:searching for reader on path usb:001:004
DEBUG:nfc.clf.transport:using libusb-1.0.22
DEBUG:nfc.clf.transport:path matches '^usb(:[0-9]{1,3})(:[0-9]{1,3})?$'
DEBUG:nfc.clf.device:loading pn533 driver for usb:04e6:5591
DEBUG:nfc.clf.device:[Errno 13] Permission denied
** found usb:04e6:5591 at usb:001:004 but access is denied
I'm not trying serial devices because you haven't told me
-- add the option '--search-tty' to have me looking
-- but beware that this may break other serial devs
Sorry, but I couldn't find any contactless device

(env) C:\SVN\NFCpython\trunk>VVV

**Comment by gerolon** [comment]
I had installed the driver with Zadic:
![image](https://user-images.githubusercontent.com/39952453/41023397-9a224df4-696c-11e8-96d5-2f5a9757621c.png)

I had some troubles with the "libusb-1.0.dll". I have copied the dlls in the 32bit and 64bit-Folders but it works only with the 32-bit Version of Python2.7. The 64-bit Python failed with nfcpy on my computer.

Now I ordered another NFC-Reader "ACR122U" to compare the behaviour.

**Comment by nehpetsde** [comment]
I could observe a similar issue on W10, different error message but also preventing a second run. For whatever reason I have not tried another reader but will do on Monday.

**Comment by gerolon** [comment]
Ok, thanks. When my new ACR122U arrived here, i will post the result

**Comment by nehpetsde** [comment]
From my tests today it looks like the issue is specific to PN533 based readers, those contain a USB stack within the chip itself. ACS122U is built upon a PN532 chip and worked fine w.r.t. multiple open/close cycles.

**Comment by gerolon** [comment]
Ok. Very good. Thank you very much for your fast support

**Comment by gerolon** [comment]
I have just tried out the ACR122U. It works!!

**Comment by muhamedhfayiz** [comment]
> Ok, thanks. When my new ACR122U arrived here, i will post the result



> I have just tried out the ACR122U. It works!!

How do you solve this issue? I have same problem with windows 10. I'm user ACR122U A9 Device.

**Comment by leonardovepe** [comment]
> > Ok, thanks. When my new ACR122U arrived here, i will post the result
> 
> > I have just tried out the ACR122U. It works!!
> 
> How do you solve this issue? I have same problem with windows 10. I'm user ACR122U A9 Device.

Hi @muhamedhfayiz , did you solve this? Having the same issue too.
