### ISSUE TITLE
SOLVED: beam.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by WatskeBart** [nfcpy/nfcpy#118]
When running beam.py with the --device argument it fails.

**beam.py: error: unrecognized arguments: --device tty:S0:pn532**

Works fine with other tools, like: tagtool.py sense.py rfstate.py

Unfortunately i'm not a python wizard, so i'm unable to spot the possible error in the code.

**Comment by nehpetsde** [comment]
This can only be due to where in the command line you've put the option. It must be before any sub-command like 'send', 'recv' etc. Try move it directly after beam.py.

**Comment by WatskeBart** [comment]
That I didn't tried that myself. It works when placing it directly after beam.py

Thanks for the quick reponse
