### ISSUE TITLE
Read multiple tags sequentially?

### ISSUE THREAD

**Issue by DanielBarreno** [nfcpy/nfcpy#134]
Is there any way to read multiple tags sequentially? (without the need to establish the connection simultaneously).
I'm using sense (only return one tag) to get the tags and i can't find a workaround to create a list of tags in the field.

Thanks for your time!

**Comment by nehpetsde** [comment]
Apologies for the late response. Working with multiple tags simultaneously is highly dependent on the tag communication technology and the reader hardware. Fundamentally there must be support for detecting and handling collisions of tag responses during the sense period and ways to systematically then mute tags that have already been found. Consumer NFC chipsets either support one or two simultaneous tags for selected technologies. So common ground is that there will only be one tag in the field at a time.
