### ISSUE TITLE
Trouble with installing pynfc on mac os

### ISSUE THREAD

**Issue by vdzhio** [nfcpy/nfcpy#143]
Heya.
I'm getting error message on `python -m pynfc`:

OSError: dlopen(libfreefare.so, 6): image not found

I brewed libfreefare, but result is still the same. Where should I get this lib?

Thank you.

**Comment by nehpetsde** [comment]
This is "nfcpy" and it doesn't use libfreefare. Better ask this question at the "pynfc" project site.

**Comment by vdzhio** [comment]
Ow, my bad :) Sorry :)
