### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by vietta90** [nfcpy/nfcpy#160]
I am having an issue importing nfc and am getting an error stating that message_decoder cannot be imported similar to a previous issue with the same error message. https://github.com/nfcpy/nfcpy/issues/88
I am using raspbian on a raspberry pi 4 with python 2.7.
I have ndeflib installed as suggested by one of the suggestion. I would appreciate any help.

**Comment by nehpetsde** [comment]
ndeflib should be automatically installed as a dependency of nfcpy, let me know if that was not the case. To verify installation, you should create and activate a Python virtual environment.
```shell
$ virtualenv -p python2 my-venv
$ . my-venv/bin/activate
$ pip install nfcpy
```

**Comment by vietta90** [comment]
Thank for the help I was able to get it to work. It was due to using sudo when running the python.
