### ISSUE TITLE
[Errno 19] No such device (Windows 10)

### ISSUE THREAD

**Issue by mb-zaba** [nfcpy/nfcpy#163]
hello,
I use the ACR1255U-J1 card reader.
So, I installed the libusb and the driver with zadig and I tried to do this in Python3  : 
```
import nfc
clf = nfc.ContactlessFrontend('usb')
```
but it always returns the error.
Doing `python3 -m nfc -vvv` returns this :
```
This is the 1.0.3 version of nfcpy run in Python 3.8.3
on Windows-10-10.0.18362-SP0    
I'm now searching your system for contactless devices
DEBUG:nfc.clf.transport:using libusb-1.0.23
DEBUG:nfc.clf.transport:path matches '^(usb|)$'
I'm not trying serial devices because you haven't told me
-- add the option '--search-tty' to have me looking
-- but beware that this may break other serial devs
Sorry, but I couldn't find any contactless device
```
How can I get it working?

**Comment by nehpetsde** [comment]
I'm sorry but this device is not yet supported. You can try how far you get with nfcpy's acr122 driver by adding the USB VID/PID in `clf/device.py` and use the [product reference manual](https://www.acs.com.hk/download-manual/7664/REF-ACR1255U-J1-1.12.pdf) to adapt the driver.
