### ISSUE TITLE
uTrust 3700F via PCSC

### ISSUE THREAD

**Issue by jaredvacanti** [nfcpy/nfcpy#174]
Is there any support for NFC devices via PCSC? When I do tests on my machine I can connect via a fresh compiled https://github.com/nfc-tools/libnfc to my reader, but the only way `nfc-list` finds the device is over PCSC (I can fully use `nfc-libs` via the PCSC connection).

Does `nfcpy` have support for PCSC (CCID-compliant) readers? If not, should I be able to connect to a https://support.identiv.com/3700f/ reader?

```
$ .venv/bin/python -m nfc
This is the 1.0.3 version of nfcpy run in Python 3.7.4
on Linux-5.4.0-45-generic-x86_64-with-debian-bullseye-sid
I'm now searching your system for contactless devices
I'm not trying serial devices because you haven't told me
-- add the option '--search-tty' to have me looking
-- but beware that this may break other serial devs
Sorry, but I couldn't find any contactless device

$ .venv/bin/python -m nfc --search-tty
This is the 1.0.3 version of nfcpy run in Python 3.7.4
on Linux-5.4.0-45-generic-x86_64-with-debian-bullseye-sid
I'm now searching your system for contactless devices
Sorry, but I couldn't find any contactless device
```

**Comment by nehpetsde** [comment]
I'm sorry, there is no support for PC/SC connected devices.
