### ISSUE TITLE
One problem on file nfcpy/docs/topics/llcp.rst

### ISSUE THREAD

**Issue by KoalaYan** [nfcpy/nfcpy#182]
According to [Wikipedia](https://en.wikipedia.org/wiki/IEEE_802.2), SAP seems to be addressed by a 8 bit numerical identifier instead of 6 bit, so I'm stuck with this problem...

**Comment by nehpetsde** [comment]
This SAP belongs yo the NFC Forum LLCP specification. What you are referring to is the 802.11 family of specifications.
