### ISSUE TITLE
Raspberry Pi and Waveshare PN532v1.6

### ISSUE THREAD

**Issue by PVTPAY** [nfcpy/nfcpy#195]
Hello, I'm trying to connect the Waveshare PN532v1.6 with a Raspberry Pi 4 B. I'm using the Pins of the Pi and no USB connection.
But when I'm starting to run the example beam.py and using the commands listed  I only get the following error message:
![image](https://user-images.githubusercontent.com/88663752/129199123-91a9ffd3-a1c3-4e2f-8232-dba11626b5ac.png)
How can I fix this? Hope you can help.

**Comment by ghxbob** [comment]
Below link may helps...
https://github.com/nfcpy/nfcpy/issues/177#issuecomment-696195538

**Comment by PVTPAY** [comment]
Yeah, I got it. It was because of lacking module installations. Everything seems to work now.
