### ISSUE TITLE
Send excel sheet to Raspy using beam.py

### ISSUE THREAD

**Issue by svenvinicius** [nfcpy/nfcpy#201]
Hi guys,

I'm trying to send an Excel Sheet over my Smartphone to a Raspberry Pi 4 using beam.py.
I tried:
`python3 beam.py --device tty:S0 recv save test.ndef`
on the Raspy and opened the Excel Sheet on my Smartphone to send it over with Android Beam. I used a ndef file, because it was recommended in the example codes.
I want to work with the excel sheet on my Raspberry Pi so I need it to be a .xlsx file. But to save the sheet as a ndef file does not seem to reach that goal.

`python3 beam.py --device tty:S0 recv save file.xlsx` also does not seem to work, because the file's content is not being saved. This is my output:

![image](https://user-images.githubusercontent.com/86777493/133634495-d2a0aa9c-84a9-46fc-afc9-4cc4f239c453.png)

Do you guys have an idea how I could fix that.

Hope you can help and greetings,
Sven

**Comment by nehpetsde** [comment]
Your smartphone is just sending a URL likely pointing to the Excel document. The URL is packaged as NDEF with the well-known-type `urn:nfc:wkt:U`. You can use https://github.com/nfcpy/ndeflib or other tools to unpack the NDEF message.
