### ISSUE TITLE
Problem with Ras pi 3 with pn532

### ISSUE THREAD

**Issue by jinzhangA** [nfcpy/nfcpy#50]
I just upgraded my pi 3 to the latest Rasbian. It turns out that they have make change to the device tree. There is no tty:S0 now and back to tty:AMA0

**Comment by nehpetsde** [comment]
I've updated yesterday and and it was then only /dev/ttyAMA0 present but used for Bluetooth. After setting "enable_uart=1" in /boot/config.txt I've got /dev/ttyS0. There's a good overview of Configuring The GPIO Serial Port On Raspbian Jessie Including Pi 3 at http://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3.

**Comment by jinzhangA** [comment]
Thank you so much! It's finally working with Pi3!
