### ISSUE TITLE
Need help with LLCP

### ISSUE THREAD

**Issue by jinzhangA** [nfcpy/nfcpy#51]
I am trying to make two Raspberry Pi talk though llpc.
At one end:
import nfc
import nfc.llcp
import threading

def server(socket):
    message, address = socket.recvfrom()
    socket.sendto("It's me!", address)
    socket.close()

def on_startup(llc):
    socket = nfc.llcp.Socket(llc, nfc.llcp.LOGICAL_DATA_LINK)
    socket.bind(address=32)
    threading.Thread(target=server, args=(socket,)).start()
    return llc

llcp_options = {
    'on-startup': on_startup,
    #'on-connect': on_connect,
}
with nfc.ContactlessFrontend('tty:AMA0:pn532') as clf:
    clf.connect(llcp=llcp_options)
    print("link terminated")

The other end:
import nfc
import nfc.llcp
import threading

def client(socket):
    socket.sendto("Hi there!", address=32)
    socket.close()

def on_connect(llc):
    socket = nfc.llcp.Socket(llc, nfc.llcp.LOGICAL_DATA_LINK)
    threading.Thread(target=client, args=(socket,)).start()
    return True

llcp_options = {
# 'on-startup': on_startup,

```
'on-connect': on_connect,
```

}
with nfc.ContactlessFrontend('tty:AMA0:pn532') as clf:
    clf.connect(llcp=llcp_options)
    print("link terminated")

This may work for the first time after reboot, but after that:
link terminated
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "caonima.py", line 6, in server
    message, address = socket.recvfrom()
  File "build/bdist.linux-armv7l/egg/nfc/llcp/socket.py", line 141, in recvfrom
    return self.llc.recvfrom(self._tco)
  File "build/bdist.linux-armv7l/egg/nfc/llcp/llc.py", line 819, in recvfrom
    return socket.recvfrom()
  File "build/bdist.linux-armv7l/egg/nfc/llcp/tco.py", line 296, in recvfrom
    raise err.Error(errno.EPIPE)
Error: nfc.llcp.Error: [EPIPE] Broken pipe

Really need some help here!

**Comment by nehpetsde** [comment]
Could you please try with "examples/beam.py send ..." and "examples/beam.py recv ..." on the both sides.

**Comment by jinzhangA** [comment]
Just tested the command you suggest.
One one side: python beam.py --device='tty:AMA0:pn532' recv print
The other side:  python beam.py --device='tty:AMA0:pn532' send text '123'

These two commands can work as the llpc ones. However, once I remove the NFC board from each other without 'ctrl+c' first, running these commands again will always say 'broken pipe'. How to fix or avoid this?

**Comment by jinzhangA** [comment]
![image](https://cloud.githubusercontent.com/assets/10929825/18790249/14876b04-817c-11e6-8f62-8f9773471ea8.png)

![image](https://cloud.githubusercontent.com/assets/10929825/18790303/449960c2-817c-11e6-851d-9d80032c72b1.png)

**Comment by jinzhangA** [comment]
After some tests, I just found out the LLCP with my setup can only work at the first time after system reboot. Any idea how to fix this?

**Comment by nehpetsde** [comment]
Have you tried with latest version from github master branch? RPi 1 or 2? Adafruit PN532 board or Elechouse?

Further the debug messages may help to understand. For beam.py that's with the `-d nfc.llcp`, `-d nfc.dep` and `nfc.clf` options, `-f <file>` to write to file, `--reltime` to look after timing issues.

**Comment by jinzhangA** [comment]
I cloned the master branch and installed it by 'sudo python setup.py install'. I guess this would give me the latest version of nfcpy. I am using Adafruit PN532 board
