### ISSUE TITLE
PN532 IRQ Pins + "card in range" var

### ISSUE THREAD

**Issue by AndiCui** [nfcpy/nfcpy#56]
Can you try to implement a funtion to turn on the PN532 interrupt IRQ pin. 
And/Or a Boolean class var or a function that tells wether a tag in range is (any technology)

**Comment by nehpetsde** [comment]
According to the documentation the P70_IRQ pin is driven automatically by the chip with behaviour depending on the host communication mode. In case of HSU link (UART) it is only ever asserted (pulled low) when the chip is in target mode waiting for activation by an external reader and would then be able to wake up the host for serving responses. It doesn't sound like this is what you're hoping for.

Presence of a tag in range can only be determined by polling (sensing) for technologies that are to be recognized (Although there are technical ways to detect when something drains energy from the RF field, none of the supported IC's has such functionality). Here's a working example that checks the presence of an Type A/B/F Tag.

```python
from nfc.clf import ContactlessFrontend, RemoteTarget
with ContactlessFrontend("usb") as clf:
    if clf.sense(RemoteTarget("106A"), RemoteTarget("106B"), RemoteTarget("212F")):
        print("found some tag")
```
