### ISSUE TITLE
Type4BTag with SCL3711 and ACR122U  not working

### ISSUE THREAD

**Issue by Crazy1Floor2** [nfcpy/nfcpy#81]
I run` tagtool.py` on windows
when I put on SCL3711 or on ACR122U Type4BTag I still see ` ** waiting for a tag **` (the nfcpy notrecognize this card).
but when i put Type2Tag I see the name of card +identifier (all is good)

why Type4BTag not working for me on SCL3711  and ACR122U  ?
i tried some kind of card and still i got that problem.

**Comment by nehpetsde** [comment]
I had only one type of Type4B card for test, so there may well be problems with some others. Please specify the cards you're using and also run tagtool with debug option and post output.

**Comment by userDevop123** [comment]
@nehpetsde
witch type of card do you try and witch reader do you use?
if i run sense.py with 106A i see None.

i run tagtool with debug and output to file but the file is empty because it stack on waiting for card.

**Comment by userDevop123** [comment]
@nehpetsde 
witch type of card do you try and witch reader do you use?
if i run sense.py with 106A i see None.

i run tagtool with debug and output to file but the file is empty because it stack on waiting for card.

**Comment by nehpetsde** [comment]
I've tested with a Texas Instruments chip that implements a so called dynamic tag with Type4B. Don't recall the name right now but can look it up tomorrow.

**Comment by StephenTiedemann** [comment]
My one and only Type4B tag is the Texas Instruments RF430CL330H NFC Booster Pack. I've just tested again reading with SCL3711, RC-S380, RC-S330, and ACR122 - worked fine.
