### ISSUE TITLE
Trying to get run tagtool.py example

### ISSUE THREAD

**Issue by Lirux** [nfcpy/nfcpy#87]
Hi

I followed the instructions on the "getting start" page to install everything.

I did it on a Raspberry 3 and Raspbian. Everything went fine, but when I start the script I get following error. 

```
Traceback (most recent call last):
  File "./tagtool.py", line 35, in <module>
    from cli import CommandLineInterface
ImportError: No module named cli
```

Could you please tell me which module I need to install? I googled around for a python CLI module and installed them but I still get this error.

Thanks.

**Comment by nehpetsde** [comment]
The missing cli module is a file in the examples directory. Just copy to the same place as tagtool.

**Comment by Lirux** [comment]
Thanks! That worked!
