### ISSUE TITLE
ACR1252 Compatibility

### ISSUE THREAD

**Issue by Kelladros** [nfcpy/nfcpy#89]
Trying to get my ACR1252 reader to connect with no success, can't seem to find device in python, or access it when directed to its exact path. Not sure if the device itself is not supported or if its an issue on my end from being a new programmer. Any help would be much appreciated, thanks.

Specifically this is what I'm getting.
tagtool.py
[nfc.clf] searching for reader on path usb
[nfc.clf] no reader available on path usb
[main] no contactless reader found on usb
[main] no contactless reader available

Process finished with exit code 1

scan.py
 line 75, in __init__
    raise IOError(errno.ENODEV, os.strerror(errno.ENODEV))
IOError: [Errno 19] No such device

using both: clf = nfc.ContactlessFrontend('USB:072F:223B:00')
and just 'usb'

**Comment by StephenTiedemann** [comment]
Have you tried `python -m nfc` as described under **Verify installation** at http://nfcpy.readthedocs.io/en/latest/topics/get-started.html#installation

**Comment by Kelladros** [comment]
Running Windows 10 64 bit. What exactly do I need to type in and what do I need to type it into? I've tried everything the installation guide says to do but just keep running into syntax errors or no results. Sorry for the trouble, and thanks for the help.

**Comment by nehpetsde** [comment]
I should have read more careful. The ACR 1252 is not supported by nfcpy. You could test if it works with the driver for ACR122 by adding the USB VID:PID to the `usb_device_map` in `nfc/clf/device.py`.

**Comment by Kelladros** [comment]
Ok, thanks for the help. It doesn't look like adding it is going to work. Going to try and find one of the readers on the compatibility list to buy online.

**Comment by nehpetsde** [comment]
The Sony RC-S380 is fully supported, /S or /P doesn't matter.

**Comment by chelinho139** [comment]
Any plans on adding support for ACR1252? Given that ACR122U is discontinued by the company and now the ACR1252 is the replacement. Thanks!

**Comment by nehpetsde** [comment]
Unfortunately I do not have this reader (and no longer a budget to buy).
