### ISSUE TITLE
beam.py can't support large file

### ISSUE THREAD

**Issue by JohnSheen** [nfcpy/nfcpy#92]
I use Android example "BeamLargeFiles" to send a file to target. But I got the below errors. And sometimes the phone show the message "The receiver can't support beam the large file."

Initator: Sony Xperia G3226 (Android 7.0) 
Target: COM3 pn532
Platform: Windows 10 + Python 2.7
Command and Parameters:   beam.py recv save xxxx.ndef
-----------------------------------------------------------------------------------------------------------------
[nfc.clf] searching for reader on path com
[nfc.clf] using PN532v1.6 at COM3
[nfc.snep.server] snep server bound to port 4 (MIU=1984, RW=15), will accept up to 1048576 byte NDEF messages
[nfc.dep] running as NFC-DEP Initiator 424F passive mode MIU=251 RWT=0.038664
[nfc.llcp.llc] LLCP Link established as NFC-DEP Initiator
Local LLCP Settings
  LLCP Version: 1.3
  Link Timeout: 500 ms
  Max Inf Unit: 2175 octet
  Link Service: connection-less and connection-oriented
  Data Protect: secure data transfer mode not supported
  Service List: 0000000000010011 (SNEP, SDP, LLC)
Remote LLCP Settings
  LLCP Version: 1.2
  Link Timeout: 1000 ms
  Max Inf Unit: 2175 octet
  Link Service: connection-less and connection-oriented
  Data Protect: secure data transfer mode not supported
  Service List: 0000000000010011 (SNEP, SDP, LLC)
[nfc.snep.server] serving snep client on remote sap 32
[nfc.dep] target requested 0.077 sec more time
[nfc.llcp.llc] ProtocolError('unrecoverable NFC-DEP error in attention request',)
Exception in thread urn:nfc:sn:snep:
Traceback (most recent call last):
  File "C:\DevTools\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\DevTools\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\DevTools\Python27\lib\site-packages\nfc\snep\server.py", line 63, in listen
    (log.debug if e.errno == nfc.llcp.errno.EPIPE else log.error)(e)
AttributeError: 'module' object has no attribute 'errno'
=================================================================
[nfc.clf] searching for reader on path com
searching for reader on path com
[nfc.clf] using PN532v1.6 at COM3
[nfc.snep.server] snep server bound to port 4 (MIU=1984, RW=15), will accept up to 1048576 byte NDEF messages
[nfc.dep] running as NFC-DEP Target 424F active mode MIU=251 RWT=0.077329
[nfc.llcp.llc] LLCP Link established as NFC-DEP Target
Local LLCP Settings
  LLCP Version: 1.3
  Link Timeout: 500 ms
  Max Inf Unit: 2175 octet
  Link Service: connection-less and connection-oriented
  Data Protect: secure data transfer mode not supported
  Service List: 0000000000010011 (SNEP, SDP, LLC)
Remote LLCP Settings
  LLCP Version: 1.2
  Link Timeout: 1000 ms
  Max Inf Unit: 2175 octet
  Link Service: connection-less and connection-oriented
  Data Protect: secure data transfer mode not supported
  Service List: 0000000000010011 (SNEP, SDP, LLC)
[nfc.snep.server] serving snep client on remote sap 32
[nfc.llcp.llc] BrokenLinkError('Error 0x29: Released by Initiator while operating as Target',)
Exception in thread urn:nfc:sn:snep:
Traceback (most recent call last):
  File "C:\DevTools\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\DevTools\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\DevTools\Python27\lib\site-packages\nfc\snep\server.py", line 63, in listen
    (log.debug if e.errno == nfc.llcp.errno.EPIPE else log.error)(e)
AttributeError: 'module' object has no attribute 'errno'

**Comment by nehpetsde** [comment]
The beam example sends data over NFC, at a maximum of about 20 KB/s. It's not really practical for large files. Furthermore, the receiver side will almost always set some limits on the maximum incoming data size, the minimum guaranteed receive capability is just 1024 byte.
